// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Expo        = require("expo");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");

function make() {
  var partial_arg = Expo.AdMob;
  return (function (param, param$1) {
      return ReasonReact.wrapJsForReason(partial_arg, param, param$1);
    });
}

exports.make = make;
/* expo Not a pure module */
