// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Expo         = require("expo");
var ReasonReact  = require("reason-react/lib/js/src/ReasonReact.js");
var Js_undefined = require("bs-platform/lib/js/js_undefined.js");

function make(onBarCodeRead, $staropt$star, $staropt$star$1) {
  var type_ = $staropt$star ? $staropt$star[0] : "back";
  var torchMode = $staropt$star$1 ? $staropt$star$1[0] : "off";
  var partial_arg = {
    onBarCodeRead: Js_undefined.from_opt(onBarCodeRead),
    type: type_,
    torchMode: torchMode
  };
  var partial_arg$1 = Expo.BarCodeScanner;
  return (function (param) {
      return ReasonReact.wrapJsForReason(partial_arg$1, partial_arg, param);
    });
}

exports.make = make;
/* expo Not a pure module */
