// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Expo                    = require("expo");
var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

function _to_string(param) {
  if (param >= 3) {
    throw [
          Caml_builtin_exceptions.match_failure,
          [
            "/Users/Edgar/Repos/bs-expo/src/permissions.re",
            16,
            2
          ]
        ];
  } else {
    switch (param) {
      case 0 : 
          return Expo.Permissions.LOCATION;
      case 1 : 
          throw [
                Caml_builtin_exceptions.match_failure,
                [
                  "/Users/Edgar/Repos/bs-expo/src/permissions.re",
                  16,
                  2
                ]
              ];
      case 2 : 
          return Expo.Permissions.CAMERA;
      
    }
  }
}

function get(permission) {
  return Expo.Permissions.getAsync(_to_string(permission));
}

exports._to_string = _to_string;
exports.get        = get;
/* expo Not a pure module */
