// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Expo        = require("expo");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");

function make(startAsync, onError, onFinish) {
  var partial_arg = {
    startAsync: startAsync,
    onError: onError,
    onFinish: onFinish
  };
  var partial_arg$1 = Expo.AppLoading;
  return (function (param) {
      return ReasonReact.wrapJsForReason(partial_arg$1, partial_arg, param);
    });
}

exports.make = make;
/* expo Not a pure module */
